"""First migration.

Revision ID: 84065306dfd9
Revises: 
Create Date: 2020-11-27 07:20:00.312841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84065306dfd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('class_music', sa.String(length=30), nullable=False),
    sa.Column('singer', sa.String(length=30), nullable=False),
    sa.Column('describe', sa.String(length=30), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('length', sa.String(length=30), nullable=False),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('rating_ball', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio')
    # ### end Alembic commands ###
